gormlog: true
mysql:
  username: "root"
  password: ""
  addr: "127.0.0.1:3306"
  name: "json2struct"
log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
addr: ":8080"